spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        highlight_sql : true

  batch:
    job:
      name: StockJob
    jdbc:
      initialize-schema: always

application:
  security:
    jwt:
      secret-key: ${SecretKey}
      expiration: 7200000 # 120 min
      refresh-token:
        expiration: 604800000 # 7 days