name: Spring Boot & Gradle CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Repository
        uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: "hollo_DB"
          mysql user: ${{secrets.DB_USER}}
          mysql password: ${{secrets.DB_PW}}
